### ISSUE TITLE
how to access flash in ejs

### ISSUE THREAD

**Issue by hezhongfeng** [ifraixedes/node-koa-flash-simple#1]
I want to access flash's value in ejs
Do you know how to do it?
Thank you.

**Comment by ifraixedes** [comment]
The flash data is attached to the context and it's accessible through the method `get` that the flash object has i.e. `const flashValue = ctx.flash.get()`

Once you have the value you can pass it as any other data to the `ejs` render.

For example, if you use [koa-views](https://github.com/queckezz/koa-views) and [koa-router](https://github.com/alexmingoia/koa-router) then you would do in your route handler something like this

```js
koa.get('/whatever', (ctx) => {
  const flashValue = ctx.flash.get()
  ctx.render('whatever-view', {
    otherData: {
        name: 'John'
    },
    flash: flashValue
  });
})
```

Bear in mind that `ctx.render` return a promise, so if you have to do any other task after the render then you should do it after the promise resolve, something like this

```js
ctx.render('whatever-view', {
   user: 'name'
})
.then(() => {
   // do whatever else here
})
```

**Comment by ifraixedes** [comment]
I hope that my previous reply clarified your doubts; it was a KOA generic topic, so I closed this issue.

**Comment by hezhongfeng** [comment]
Thank you for your answer.
I have known how to use it.
